name: CI/CD Pipeline

on:
  push:
    branches:
      - Python

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/$IMAGE_NAME .
        docker tag ${{ secrets.DOCKER_REGISTRY }}/$IMAGE_NAME ${{ secrets.DOCKER_REGISTRY }}/$IMAGE_NAME
        docker push ${{ secrets.DOCKER_REGISTRY }}/$IMAGE_NAME
      env:
        IMAGE_NAME: hello-world-pyspark

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        kubectl apply -f deployment.yaml --namespace default
        kubectl rollout status deployment/hello-world-pyspark-deployment --namespace default
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
